SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_SPAWN = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_RESOLUTION = 16 # Lines per asteroid
ASTEROID_SPICKYNESS = 1 # How many spikes. Lower means more. 
ASTEROID_SPICKYNESS_FACTOR = 0.80 # How extreme the spikes are. Lower is more extreme.

PLAYER_RADIUS = 20
PLAYER_MAX_SPEED = 300  # pixels per second
PLAYER_ACCELERATION = 1  # pixels per second^2
PLAYER_DEACCELERATION = 2  # pixels per second^2
PLAYER_TURN_SPEED = 300  # degrees per second
PLAYER_SHOOT_SPEED = 500  # pixels per second
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_LIVES = 3

POWERUP_RADIUS = 10
POWERUP_MAX_SPAWN = 2
POWERUP_SPAWN_RATE = 5  # seconds
POWERUP_SPEED_BOOST_TIMER = 5
POWERUP_SPEED_BOOST = 2
POWERUP_SPREAD_TIMER = 5

SHOT_RADIUS = 5
SHOT_SPREAD_AMOUNT = 5 # degrees

SCORE_TIME_BONUS = 100  # points per second

EXTRA_LIFE_SCORE = 20000  # points